[package]
name = "pocketflow-rs"
version = "0.1.0"
edition = "2024"
authors = ["echozyr2001 <echo.zyr.2001@gmail.com>"]
description = "A Rust implementation of PocketFlow framework"
license = "MIT"

# [features]
# default = []
# parallel = ["dep:rayon"]

[dependencies]
# rayon = { version = "1.10", optional = true }
rayon = "1.10"
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
anyhow = "1.0"
thiserror = "2.0"
tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
parking_lot = "0.12"

[dev-dependencies]
utils = { path = "./utils" }
tokio-test = "0.4"
openai = "1.1.0"
