[package]
name = "utils"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
openai = "1.1.0"
dotenvy = "0.15"
anyhow = "1.0"
openai_api_rust = { path = "../openai-api" }
